---
repos:
  - repo: https://github.com/adrienverge/yamllint
    rev: v1.26.3
    hooks:
      - id: yamllint
        files: \.(yml|yaml|talismanrc)$
        types: [file, yaml]
        exclude: kitchen\.ya?ml$
        entry: yamllint --strict
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.62.3
    hooks:
      - id: terraform_fmt
      - id: terraform_docs
        args: ['--args=--sort-by=required --hide=providers']
  - repo: https://github.com/jumanjihouse/pre-commit-hooks
    rev: 2.1.5
    hooks:
      - id: bundler-audit
      - id: reek
      - id: rubocop
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: check-executables-have-shebangs
      - id: check-merge-conflict
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: trailing-whitespace
  # Talisman pre-commit hook declaration is broken; pre-commit cannot build from
  # source. Use the talisman binary installed in container/user environment.
  - repo: local
    hooks:
      - id: local-talisman
        name: talisman
        entry: talisman --githook pre-commit
        stages:
          - commit
        pass_filenames: false
        types:
          - text
        language: system
