---
extends: default
ignore:
  - modules/template/templates/cloud-config.yaml
  - tests/template/templates/cloud-config.yaml
rules:
  line-length:
    max: 120
    ignore:
      - tests/stateless/files/runtime-init-conf-1nic.yaml
      - tests/stateless/files/runtime-init-conf.yaml
      - tests/files/runtime-init-conf.yaml
      - examples/**/templates/runtime-init-conf.yaml
